// @ts-nocheck
// Auto-generated by pcg build — do not edit
const config = {
  default: {
    override: {
      wrapper: () => import("./.pcg/overrides/adapters/wrappers/node-server.js").then(m => m.default),
      converter: () => import("./.pcg/overrides/adapters/converters/passthrough.js").then(m => m.default),
      incrementalCache: () => import("./.pcg/overrides/overrides/incrementalCache/gateway.js").then(m => new m.default()),
      tagCache: () => import("./.pcg/overrides/overrides/tagCache/gateway.js").then(m => new m.default()),
      queue: "direct",
      proxyExternalRequest: "fetch",
    },
  },
  imageOptimization: {
    install: false,
  },
  buildOutputPath: ".",
  appPath: ".",
};

export default config;
